### ISSUE TITLE
Proof read website content

### ISSUE THREAD

**Issue by lifenautjoe** [OpenBookOrg/www.open-book.org#21]
Give the site content a full blown read and note points to improve or refactor.

**Comment by lifenautjoe** [comment]
@evict , @bmaia could you guys help me proofread the index.html?

**Comment by lifenautjoe** [comment]
On the branch feature/21-proofread

**Comment by evict** [comment]
Hereby my feedback. In general I like 'We are' more than "We're" but this is personal thingy.

### Openness

'anyone could setup their own and carry on with the mission.'

To:

'anyone could setup their own instance and carry on with the mission.'

### Privacy and security

'Given our cyber security background'

I personallly hate the cyber word:

'Given our background in information security'


'We will embed privacy and security in the core of everything we do.'

To:

'Privacy and security will be at the core of everything we do.'

#### Data sharing

##### Problem 1

'When you do, you'll get some more information.'

To:

'When you do, you will get some more information.'


'Apart from wondering why in the world would a WiFi hotspot need any of these, it is still not clear what data will be shared.'

To:

'Apart from wondering why in the world would a WiFi hotspot need any of this, it is still not clear what data will be shared.'

##### Problem 2

'This is the current case in every social media.'

To:

'This is currently the case with all social media.'


'You register an application, configure what information the application "needs" from your users, and you're done.'

To:

'You reigster with an application ... '

and I would consider "you're" -> "you are". 


'Well, in a perfect world where all humans have good intentions for others this would work.'

To:

'Well, in a perfect world where all humans have good intentions towards others this would work.'

'Social media companies should be responsible for ensuring applications do not abuse data sharing systems.'

To:

'Social media companies should be responsible for ensuring that applications do not abuse data sharing systems.'

'All applications requesting access to user data should be closely examined, by real people, with the privacy and security of their users as their guiding principles.'

To:

'All applications requesting access to a user's data should be closely examined, by real people, with the privacy and security of their users as their guiding principles.'

##### Problem 3

'Could you un-athorize the data sharing?'

To:

'Could you unauthorize the data sharing?'

Or:

'Could you undo the authorization of data sharing?'

'Once the data is shared, there's no going back'

To:

'Once the data has been shared, there is no going back'


##### Solution

'Here's our prototype. Go head click around.'

To:

'Here is our prototype. Go ahead click around.'

'That is why we want to make sure it's always crystal clear what is to be shared.'

To:

'That is why we want to make sure it is always crystal clear what is to be shared.'


##### Safe applications

'revoke it's access and most..'

To:

'revoke its access and most..'

##### Goodbye data sharing

'P.D. You will recognize'

To:

'P.S. You will recognize'

Thinking you might meant to say P.S.?

#### No tracking

'Although we're fans of the Do Not Track initiative. We strongly believe no "Opt-out" should be necessary for people not to be monitored across the internet.'

To:

'Although we are fans of the Do Not Track initiative. We strong believe security and privacy should be "Opt-in", and not "Opt-out". You deserve to wander around the internet unmonitored.'

#### FAQ

##### How will you make money?

'We will build Openbook to be a platform for peer to peer services such as products and services marketplaces.'

To:

'We will build Openbook to be a platform for peer-to-peer services such as product and service marketplaces.'

'For example, you could sell your beloved Star Wars DVD collection in the network in the same way you could hire someone to walk your dog.'

To:

'For example, you could sell your beloved Star Wars DVD collection on the network in the same way you could hire someone to walk your dog.'

'Applications built in the platform will benefit from the privacy and security of the ecosystem.'

To:

'Applications built within the platform will benefit from the privacy and security of the ecosystem.'

##### What if funding goals

'And finally, we hope they realise new ways of making money can be thought of that don't involve personal information....'

To:

'And finally, we hope they realize new ways of making money that does not involve monetizing personal information without informed consent.'

**Comment by lifenautjoe** [comment]
Very good! I Thanks! At quick sight I'll add some 95% of these to the page.

**Comment by lifenautjoe** [comment]
Website is live with proofread content by 6 different individuals!
